{
 "title": "DefectDojo Exporter",
 "description": "https://github.com/iamhalje/defectdojo-exporter",
 "tags": [ "DefectDojo" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "product_type",
    "label": "ProductType",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active,product_type)"
    }
   },
   {
    "name": "product",
    "label": "Product",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active{product_type=~\"$product_type\"},product)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active{product_type=~\"$product_type\", product=~\"$product\"},severity)"
    }
   },
   {
    "name": "cwe",
    "label": "CWE",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\"},cwe)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_active{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Duplicate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_duplicate{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "False Positive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(product, severity)  (dojo_vulnerabilities_false_positive{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Out Of Scope",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_out_of_scope{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Risk Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_risk_accepted{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Under Review",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(product, severity)  (dojo_vulnerabilities_under_review{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Verified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_verified{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Mitigated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_mitigated{product_type=~\"$product_type\", product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  }
 ]
}